#!/usr/bin/env bash
# gen-initiatives-index.sh — regenerate docs/40-initiatives/README.md from
# each initiative's frontmatter.
#
# Usage: gen-initiatives-index.sh [DOCS_DIR] [OUTPUT_FILE]
#   DOCS_DIR     defaults to "docs"; the index lives at DOCS_DIR/40-initiatives/README.md
#   OUTPUT_FILE  defaults to DOCS_DIR/40-initiatives/README.md; pass a temp
#                path (e.g. from check-initiatives.sh) to regenerate without
#                touching the real file.
#
# Any hand-written prose above a line containing exactly
# "<!-- BEGIN GENERATED INDEX -->" in the existing index is preserved
# verbatim above the regenerated table. If no existing index (or no marker)
# is found, a minimal preamble is created.
#
# Output is deterministic (initiative folders sorted lexically) so that
# check-initiatives.sh's R7 diff is stable across runs.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib-initiatives.sh
source "$SCRIPT_DIR/lib-initiatives.sh"

DOCS_DIR="${1:-docs}"
INIT_DIR="$DOCS_DIR/40-initiatives"
TARGET="$INIT_DIR/README.md"
OUTPUT_FILE="${2:-$TARGET}"

BEGIN_MARKER="<!-- BEGIN GENERATED INDEX -->"
GENERATED_MARKER="<!-- GENERATED by gen-initiatives-index.sh — do not hand-edit below this line -->"

if [ ! -d "$INIT_DIR" ]; then
  echo "gen-initiatives-index.sh: no such directory: $INIT_DIR" >&2
  exit 1
fi

# --- Preserve any hand-written preamble above the BEGIN marker. ---------
preamble=""
if [ -f "$TARGET" ] && grep -qF "$BEGIN_MARKER" "$TARGET"; then
  preamble="$(awk -v marker="$BEGIN_MARKER" '
    { if (index($0, marker) > 0) { print; exit } print }
  ' "$TARGET")"
else
  preamble="# Initiatives Index

$BEGIN_MARKER"
fi

# --- Collect initiative directories, sorted lexically by folder name. ---
dirs="$(find "$INIT_DIR" -mindepth 1 -maxdepth 1 -type d ! -name '.*' -print | sort)"

# --- Build the table. ----------------------------------------------------
table="$(printf '%s\n' \
  "$GENERATED_MARKER" \
  "" \
  "| Folder | Title | Status | Owner | Note |" \
  "| --- | --- | --- | --- | --- |")"

if [ -n "$dirs" ]; then
  while IFS= read -r dir; do
    [ -z "$dir" ] && continue
    name="$(basename "$dir")"
    readme="$dir/README.md"

    title=""
    status=""
    owner=""
    note=""
    if [ -f "$readme" ]; then
      title="$(read_frontmatter_field "$readme" title)"
      status="$(read_frontmatter_field "$readme" status)"
      owner="$(read_frontmatter_field "$readme" owner)"
      note="$(read_frontmatter_field "$readme" status_note)"
    fi

    [ -z "$title" ] && title="—"
    [ -z "$status" ] && status="—"
    [ -z "$owner" ] && owner="—"
    [ -z "$note" ] && note="—"

    table="$table
| \`$(escape_md_pipes "$name")/\` | $(escape_md_pipes "$title") | $(escape_md_pipes "$status") | $(escape_md_pipes "$owner") | $(escape_md_pipes "$note") |"
  done <<< "$dirs"
fi

printf '%s\n\n%s\n' "$preamble" "$table" > "$OUTPUT_FILE"
